name: Build terstys

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Create build directory
      run: |
        mkdir build

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Install
      run: cmake --install build --prefix install
    
    - name: Archive install directory (for release)
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        tar -czf terstys-${{ github.ref_name }}.tar.gz -C install .

    - name: Upload release asset
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: terstys-${{ github.ref_name }}.tar.gz